### ISSUE TITLE
Cached images corrupted

### ISSUE THREAD

**Issue by legarland** [zyra/ionic-image-loader#71] opened 2017-06-26 15:35 UTC
I'm having an issue where some images are being saved/retrieved from the cache incompletely. Part of the image will show and the rest will just be a solid gray background. If i kill the app and relaunch the images are returned in the same way. Here is an example.

![img_0631](https://user-images.githubusercontent.com/375064/27547248-3b15e3ca-5a4a-11e7-857b-0bd345d471b0.PNG)

**Comment by ihadeed** [comment] 2017-06-27 04:55
Thanks for reporting this.

I was aware of this issue before but I wasn't able to diagnose it and figure out the root of the problem. It seems to happen if the images are still loading (probably a slow connection or very large images), and you switch to a different page in the app or close it. I doubt that this is the issue though, because everything happens in the background and it doesn't depend on the component being rendered or not.

I will look into this more when I get a chance. If you come across anything that you think might be causing this, please let me know. The more information I have the better.

**Comment by legarland** [comment] 2017-06-28 15:32
Thanks for the reply. As far as I can tell the issue less frequent, or perhaps goes away entirely, when setting `imageLoaderConfig.setImageReturnType('base64');` This is the current solution I am using.

**Comment by shajeeck** [comment] 2017-07-13 09:01
I am also having same problem, it happens when app is closed of page changed while saving images.
@legarland i tried to use `imageLoaderConfig.setImageReturnType('base64');` but the image is not displayed, i am using `<img-loader src="https://path.to/my/image.jpg"></img-loader>` 

how did you make it work?

**Comment by shajeeck** [comment] 2017-07-13 09:08
@ihadeed i tried using imgcache.js before your plugin, i faced the same issue. broken images are loaded when app is closed or navigated to another page. This was the reason i tried your plugin, but same issue here. Any updates?

**Comment by germanurrus** [comment] 2017-08-11 16:24
I'm having the same issue with images, when a cached image is loaded it brings half of it and the rest is black...

**Comment by matthieu80** [comment] 2017-08-16 17:26
this is working for me:
imageLoaderConfig.setImageReturnType('base64');
thanks @legarland

**Comment by stephenandrews** [comment] 2017-08-25 10:23
I'm having the same issue - I'm looking at doing the following:

-When downloading the image natively, we store it as image.jpg.tmp
-When download is completed, we rename by removing the .tmp
-Will also run a script during the initial init process to remove old .tmp files too?

I think the issue occurs because we download the file as image.jpg, and if the download is interrupted (which seems to occur more for bigger applications) it continues to serve the half downloaded image.

**Comment by stephenandrews** [comment] 2017-08-25 12:21
I made some changes to a fork: https://github.com/stephenandrews/ionic-image-loader

I ran some tests, and we no longer get the issue at present. Files are downloaded with "_t" appended to the end of the filename, and upon completion and renamed ("_t" removed) and then served.

**Comment by matthieu80** [comment] 2017-08-28 14:16
@stephenandrews
That s a great news if your fork works. I have problem to install it though...
Here is the command:
npm install "git+https://github.com/stephenandrews/ionic-image-loader.git" --save

I get a "cannot find the module" error for "ionic-image-loader" :-/

**Comment by patricktyndall** [comment] 2017-10-17 17:08
@matthieu80 did you figure out how to build his fork? getting the same error - missing the /dist directory after i install it.

@stephenandrews can you publish to npm, or provide build instructions?

**Comment by patricktyndall** [comment] 2017-10-17 17:36
@matthieu80 forked and built it myself (and made a small bug fix that was preventing build):

npm install "git+https://github.com/patricktyndall/ionic-image-loader.git" --save

it works better, but i do still experience the issue (just with less frequency).

@stephenandrews thanks for your work..

**Comment by ihadeed** [comment] 2017-10-17 21:46
- Can you guys confirm that @stephenandrews 's fork fixes this issue?
- Is there a proper way to reproduce this issue? or does it happen randomly?

**Comment by stephenandrews** [comment] 2017-10-17 22:07
@ihadeed @patricktyndall I made some additional changes which, for my application at least, resolved the issue completely. I was still getting some odd instances where some images were still corrupted, but after the last change it seemed to fix it.

I'll try get my changes and merge it with @patricktyndall fork and see if that see any improvements

**Comment by bhavincb** [comment] 2017-11-06 08:44
@stephenandrews  can you share complete solution you build!

**Comment by Alb93** [comment] 2017-12-09 13:34
News here? Same problem for me.

**Comment by felixbroehl** [comment] 2018-06-11 21:16
Still having this issue. Perfomance-wise i don't want to present my images in base64.

**Comment by ihadeed** [comment] 2018-09-17 05:46
Closing, please let me know if this is still an issue with the latest version.

**Closed** 2018-09-17 05:45 UTC
