### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by macklus** [zyra/ionic-image-loader#183] opened 2018-08-06 09:55 UTC
Hi:

I using:

- Ionic: 4.0.3
- Ionic Framework: ionic-angular 3.9.2
- Ionic image Loader:  5.0.5

when i try to load an image, i get error:

"Not allowed to load local resource: file:///data/user/0/MI_APP_ID/cache/image-loader-cache/-919523643", source: http://localhost:8080/ (0) 

any hint about this problem ?

thanks in advance.

**Comment by Ross-Rawlins** [comment] 2018-08-07 12:43
Got this same issue on android did you resolve it?

**Comment by macklus** [comment] 2018-08-07 15:12
How do you do that ?
Anyway, i hope problem can be solved, latest webview is better than old one

**Comment by mateusknob** [comment] 2018-08-07 16:58
Having the same issue over here on a Android device (on browser works fine)

**Comment by mateusknob** [comment] 2018-08-07 17:50
setting the return type to base64 works!

`this.imageLoaderConfig.setImageReturnType('base64');`

it's not a permanent solution, but...

**Comment by macklus** [comment] 2018-08-07 18:27
@mateusknob can this option be globaly configure ?

**Comment by mateusknob** [comment] 2018-08-07 19:10
@macklus yes, check this section:

https://github.com/zyra/ionic-image-loader#global-configuration

**Comment by freelancersunil** [comment] 2018-08-21 08:03
You need to perform 2 actions to resolve.
a) install https://cloud.google.com/storage/docs/gsutil_install
b) browse to the home directory where you instal google cloud sdk (a) above > gsutil
c) Run in terminal >  gsutil cors set cors.json gs://<your bucket ID path>

Then 
```
import { ImageLoaderConfig } from 'ionic-image-loader';
constructor(
private imageLoaderConfig: ImageLoaderConfig) {
 this.imageLoaderConfig.setImageReturnType('base64');
}
```

Ref: Documents : 
a) https://firebase.google.com/docs/storage/web/download-files
b) https://cloud.google.com/storage/docs/gsutil_install

**Comment by freelancersunil** [comment] 2018-08-21 08:06
@mateusknob - your solution worked with an extra research and more steps implemented as above, thanks!

**Comment by Shtibel** [comment] 2018-09-03 09:58
Can confirm.
The new ionic webview plugin is the cause for the problem.
The new plugin: cordova-plugin-ionic-webview @ 2.x seem unstable...

I downgraded back to cordova-plugin-ionic-webview@1.2.1 and all works grate.

Steps:
1. uninstall webview
`ionic cordova plugins rm cordova-plugin-ionic-webview`

2. install old one:
`ionic cordova plugins add cordova-plugin-ionic-webview@1.2.1`

3. clean cordova
`cordova clean android`

**Comment by macklus** [comment] 2018-09-04 08:15
just for confirm, solution of @mateusknob is working ??
i do prefer do that before downgrade webview

**Comment by Shtibel** [comment] 2018-09-04 09:05
Hi @macklus 
I can confim this is working for me

**Comment by macklus** [comment] 2018-09-07 08:03
@Shtibel sadly, its not working for me.
can you please paste your package.json file to compare ?
thanks

**Comment by shriniwasb** [comment] 2018-09-10 07:51
Hi,
Use this 
window.Ionic.WebView.convertFileSrc(localFilePath)

**Comment by SmirnovM91** [comment] 2018-09-13 07:10
> Hi,
> Use this
> window.Ionic.WebView.convertFileSrc(localFilePath)

Where should I use it?

**Comment by shriniwasb** [comment] 2018-09-13 07:56
Hi @SmirnovM91,

Cordova and Capacitor apps are hosted on a local HTTP server and are served with the http:// protocol. Some plugins, however, attempt to access device files via the file:// protocol. To avoid difficulties between http:// and file://, paths to device files must be rewritten to use the local HTTP server. For example, file:///path/to/device/file must be rewritten as http://<host>:<port>/<prefix>/path/to/device/file before being rendered in the app.

For Cordova apps, the Ionic Web View plugin provides a utility function for converting File URIs: window.Ionic.WebView.convertFileSrc(). There is also a corresponding Ionic Native plugin: @ionic-native/ionic-webview.

Please check this below link
https://beta.ionicframework.com/docs/building/webview/

**Comment by ihadeed** [comment] 2018-09-17 07:13
Is this still an issue with the latest releasE?

**Comment by flore2003** [comment] 2018-09-19 20:34
Yes, it is. I traced it down to the `getCachedImagePath` method in `image-loader.ts`. It checks the `isIonicWKWebView` getter, which in turn checks the `isWKWebView` getter, which only evaluates to true on iOS. When using Ionic on Android, the file URI is never transformed for Ionic and thus the error is thrown. I might be able to create a pull request later today, if you would be interested in having this issue fixed :slightly_smiling_face:

**Comment by flore2003** [comment] 2018-09-19 20:56
There it is :point_up:

**Comment by madoBaker** [comment] 2018-09-19 21:16
Thank you @flore2003 for your contribution! PR merged and issue closed

**Closed** 2018-09-19 21:16 UTC
Labels: needs reply

**Comment by b1ueRa1n** [comment] 2018-11-27 11:37
@Shtibel  Thank you very much! The new ionic webview plugin is the cause for the problem.

**Comment by b1ueRa1n** [comment] 2018-11-28 03:37
Yes, I had found another solution.  

in .html
<img [src]="getTrustImg(imageSrc)" />

in .ts
 private win: any = window;

  getTrustImg(imageSrc){
    let path = this.win.Ionic.WebView.convertFileSrc(imageSrc);
    console.log(path);
    return path;
  }

**Comment by Sampath-Lokuge** [comment] 2018-12-07 15:12
This is the version where it works for me on `Ionic 3.9.2` app.

https://github.com/ionic-team/cordova-plugin-ionic-webview/releases/tag/v1.2.1

**Comment by borodatych** [comment] 2018-12-20 10:18
`
import { normalizeURL } from 'ionic-angular';
...
this.camera.getPicture(options).then((imageUri:any) => {
                imageUri = normalizeURL(imageUri);
...
`

**Comment by pcsantana** [comment] 2019-01-08 19:33
Hi!
Is this still an issue?

After a update the cordova-plugin-ionic-webview to 2.x , the image stopped to load, but no errors throws.
The path is like it:
`http://localhost:8080/_file_/data/user/0/<app_id>/cache/image-loader-cache/-601073275 `

Any idea?
Thank you!

**Comment by pengkobe** [comment] 2019-01-11 08:51
after i using `convertFileSrc` to transform url. my logs shows `Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME`

**Comment by b1ueRa1n** [comment] 2019-01-13 14:09
> after i using `convertFileSrc` to transform url. my logs shows `Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME`. anyone got any ideas?

What is your local file path?

**Comment by giovannipds** [comment] 2019-01-25 19:40
Use [this](https://beta.ionicframework.com/docs/native/ionic-webview/) and be happy. **Do not downgrade** as proposed by @Shtibel anymore, there's already a solution:
```sh
ionic cordova plugin add cordova-plugin-ionic-webview
npm install --save @ionic-native/ionic-webview@beta
```
```typescript
import { WebView } from '@ionic-native/ionic-webview/ngx';

constructor(private webview: WebView) { }
...
img = this.webview.convertFileSrc('file:///Users/dan/camera-image-12345.png')
```
:heart:

**Comment by Sampath-Lokuge** [comment] 2019-01-26 09:46
@giovannipds Your solution will not work with the Ionic 3 app since it requires ionic native 5+ with Angular 7+. So need to use webview 3+ without Ionic native like so: https://stackoverflow.com/a/54269144/1077309

**Comment by brenden-t-r** [comment] 2019-03-07 17:48
> Use [this](https://beta.ionicframework.com/docs/native/ionic-webview/) and be happy. **Do not downgrade** as proposed by @Shtibel anymore, there's already a solution:
> 
> ```shell
> ionic cordova plugin add cordova-plugin-ionic-webview
> npm install --save @ionic-native/ionic-webview@beta
> ```
> 
> ```ts
> import { WebView } from '@ionic-native/ionic-webview/ngx';
> 
> constructor(private webview: WebView) { }
> ...
> img = this.webview.convertFileSrc('file:///Users/dan/camera-image-12345.png')
> ```
> 
> Note: do not forget to register `Webview` at your `.module`.
> 
> ❤️

After hours of trying a million suggestions, this is what worked. For me I had to also force imgcache.js to return toURL() instead of toInternalURL(). I'm using Ionic 4 for reference.

**Comment by derman10** [comment] 2019-04-09 20:01
> Can confirm.
> The new ionic webview plugin is the cause for the problem.
> The new plugin: cordova-plugin-ionic-webview @ 2.x seem unstable...
> 
> You can follow the issue I opened there:
> [ionic-team/cordova-plugin-ionic-webview#158](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/158)
> 
> I downgraded back to cordova-plugin-ionic-webview@1.2.1 and all works grate.
> 
> Steps:
> 
> 1. uninstall webview
>    `ionic cordova plugins rm cordova-plugin-ionic-webview`
> 2. install old one:
>    `ionic cordova plugins add cordova-plugin-ionic-webview@1.2.1`
> 3. clean cordova
>    `cordova clean android`
> 
> By the way `angular-cropperjs` is also not working with the new webview.

doing this broken all the image of the project.

**Comment by CraigAndrew** [comment] 2019-06-20 20:37
What worked for me is simply going to the package.json file of my project root, updating the "cordova-plugin-ionic-webview" entry like so:
`"cordova-plugin-ionic-webview": "2.0.0-beta.2",`

Then run the 2 commands:
```
npm i
ionic cordova run android
```

**Comment by mshallaq** [comment] 2020-02-03 15:45
the best solution to this problem is to start using Visual Studio and then install a Live Server Extention then go live command from the footer of the page.

**Comment by azad47808** [comment] 2020-02-20 12:59
private win: any = window;

let savePath = this.win.Ionic.WebView.convertFileSrc(path);

**Comment by usamahashmii** [comment] 2020-10-02 10:33
> Can confirm.
> The new ionic webview plugin is the cause for the problem.
> The new plugin: cordova-plugin-ionic-webview @ 2.x seem unstable...
> 
> You can follow the issue I opened there:
> [ionic-team/cordova-plugin-ionic-webview#158](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/158)
> 
> I downgraded back to cordova-plugin-ionic-webview@1.2.1 and all works grate.
> 
> Steps:
> 
> 1. uninstall webview
>    `ionic cordova plugins rm cordova-plugin-ionic-webview`
> 2. install old one:
>    `ionic cordova plugins add cordova-plugin-ionic-webview@1.2.1`
> 3. clean cordova
>    `cordova clean android`
> 
> By the way `angular-cropperjs` is also not working with the new webview.
