### ISSUE TITLE
bug(5.0.3): Images not showing

### ISSUE THREAD

**Issue by eduardoRoth** [zyra/ionic-image-loader#168] opened 2018-07-03 03:00 UTC
Images are downloaded but not updated on screen. Images seem to be cached but not shown.
I'll update as soon as I have more detail.

**Comment by eduardoRoth** [comment] 2018-07-03 03:30
1. Image download start as usual.
2. Image's XHR calls finish with status code 200 (only 5)
3. I have two GIFs that keep loading even after the XHR call is finished
4. Component is not updated, keeps showing spinner

**Comment by eduardoRoth** [comment] 2018-07-03 23:12
More details about this error:

1. Open app
2. App inits Image Loader configuration
      ```
        this._image.setMaximumCacheSize(268435456);
        this._image.enableDebugMode();
        this._image.setCacheDirectoryName('custom-name');
        this._image.setFileNameCachedWithExtension(true);
      ```
3. App sets root to page
4. Page load calls API
5. API returns five items
6. Image Loader starts fetching image
7. Spinner stuck loading
8. Close app after a while
9. Open app again, ImageLoader fetch from cache but image is not available (although no error)
10. Move to another page
11. New page call API and gets 5 different results
12. ImageLoader load everything fine.

**Comment by eduardoRoth** [comment] 2018-07-04 01:01
On first run, something is happening in `processQueue` function that it never resolves or rejects in this part:

```
_this.file.writeFile(localDir, fileName, data)
                    .then(function (file) {
                        if (_this.shouldIndex) {
                            _this.addFileToIndex(file).then(function () {
                                _this.getCachedImagePath(currentItem.imageUrl).then(function (localUrl) {
                                    currentItem.resolve(localUrl);
                                    resolve();
                                    done();
                                    _this.maintainCacheSize();
                                }).catch(err => {
                                    console.error('currentItem', err);
                                    currentItem.reject();
                                });
                            });
                        }
                    }).catch(function (e) {
                        //Could not write image
                        console.error(e);
                        reject();
                        error(e);
                    });
```

**Comment by gmosornoza** [comment] 2018-07-04 15:13
Hi, same issue over here. Any news?

**Comment by gmosornoza** [comment] 2018-07-04 16:35
What i'm seeing is that the files are created with 0 filesize.

**Comment by eduardoRoth** [comment] 2018-07-04 16:39
@gmosornoza but it only happens the first time, if you close your app (fully close it) and then navigate to another page that has `img-loader` components, they'll load just fine.

**Comment by gmosornoza** [comment] 2018-07-04 16:44
@eduardoRoth Not for me.  In fact, first time only shows the fallback Image.  If i close and reopen the app, then it shows the image as broken image.

Checking the cache directory in the device i noticed the zero filesize.

**Comment by eduardoRoth** [comment] 2018-07-04 16:57
First time opening the app:
![image](https://user-images.githubusercontent.com/5419161/42288572-e8752498-7f80-11e8-9ed5-89a607f8848e.png)

Second time opening the app - **confirms the zero byte files**:
![image](https://user-images.githubusercontent.com/5419161/42288607-0cf67966-7f81-11e8-97d8-5801d47d3cf4.png)

**Comment by eduardoRoth** [comment] 2018-07-04 17:19
![image](https://user-images.githubusercontent.com/5419161/42289217-ec9dffc4-7f83-11e8-806e-069c4e9f260c.png)

**Comment by eduardoRoth** [comment] 2018-07-04 17:20
This happens both with `@ionic-native` **4.7.0** or **4.9.0**

**Comment by felixbroehl** [comment] 2018-07-04 17:50
Did this worked before my changes were merged? Which platforms did you tested? I'm unable to reproduce such problems with my devices.

**Comment by gmosornoza** [comment] 2018-07-04 18:09
@felixbroehl I'm using the plugin as is. Android Oreo device,

**Comment by gmosornoza** [comment] 2018-07-04 18:42
window.resolveLocalFileSystemURL is rejecting with errorCode 1, in cordova-plugin-file.

I trace until this:

File.prototype.resolveLocalFilesystemUrl = function (fileUrl) {
        var _this = this;
        return new Promise(function (resolve, reject) {
            try {
                window.resolveLocalFileSystemURL(fileUrl, function (entry) {
                    resolve(entry);
                }, function (err) {
                    _this.fillErrorMessage(err);
                    reject(err);
                });
            }
            catch (xc) {
                _this.fillErrorMessage(xc);
                reject(xc);
            }
        });
    };

**Comment by eduardoRoth** [comment] 2018-07-04 20:03
@felixbroehl Samsung S8 - Oreo 8.0.0

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-plugin-proxy : 1.5.8
    @ionic/cli-utils        : 1.19.2
    ionic (Ionic CLI)       : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 7.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 7.0.0
    Node       : v8.11.1
    npm        : 6.1.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME     : not set
    HTTP_PROXY       : not set
    http_proxy       : not set
    HTTPS_PROXY      : not set
    https_proxy      : not set
    IONIC_HTTP_PROXY : not set
    PROXY            : not set
    proxy            : not set

Misc:

    backend : legacy
```

**Comment by eduardoRoth** [comment] 2018-07-04 20:45
@gmosornoza @felixbroehl checked my app settings and found that it had the "Storage" permission off, so I turned it on and tried again with no result... So I disallowed it again and suddendly it started working... really strange

Will check on it further...

**Comment by felixbroehl** [comment] 2018-07-04 20:48
ok this is strange :D

**Comment by felixbroehl** [comment] 2018-07-04 20:48
seems more like a problem with cordova than with this plugin

**Comment by eduardoRoth** [comment] 2018-07-04 21:04
Cleared cache again for my app and tried again... same problem 😢

**Comment by felixbroehl** [comment] 2018-07-04 21:15
this could be related to https://github.com/ionic-team/ionic-native/issues/806

**Comment by felixbroehl** [comment] 2018-07-04 21:21
could you try this hack described by joewoodhouse? https://github.com/ionic-team/ionic-native/issues/505

> So, I've found a fix (I think) is to re-order the index.html of your app so that the polyfills.js (which includes zone.js and a few other things) is included before cordova.js. This seems to make it work reliably for me. Presumably this gives some clue as to what's going on, something to do with how zone.js patches things?

**Comment by eduardoRoth** [comment] 2018-07-04 21:38
@felixbroehl was just trying this change, and it seems to *partially* fix this issue. I need to use `setMaximumCacheSize()` function to set a maximum cache.

Tried both ways, with and without `setMaximumCacheSize()` and only with it, the images were loaded.

**setMaximumCacheSize https://github.com/zyra/ionic-image-loader/issues/27#issuecomment-401957582**
![image](https://user-images.githubusercontent.com/5419161/42294679-7e35cbc8-7fa8-11e8-966a-0a0c9f5b2026.png)


Is there any drawback to have the `polyfills.js` loaded before cordova?

**Comment by eduardoRoth** [comment] 2018-07-04 21:39
@gmosornoza could you try both *fixes* and see if it works for you know?

**Comment by felixbroehl** [comment] 2018-07-04 21:40
maybe this also is related to "if(this.shouldIndex)" and no else in your example

**Comment by felixbroehl** [comment] 2018-07-04 21:42
because this.shouldIndex is defined by the maximumCacheSize

**Comment by eduardoRoth** [comment] 2018-07-04 21:45
Yeah, just removed that `if(this.shouldIndex)` and it worked without setting a `maximumCacheSize`.

Why is there this property? @ihadeed

**Comment by felixbroehl** [comment] 2018-07-04 21:52
also wtf is this:
`(this.config.maxCacheAge > -1) || (this.config.maxCacheSize > -1)`
this means that maximumCacheSize should be set. @ihadeed what was this intended for?

**Comment by felixbroehl** [comment] 2018-07-04 22:03
there should be something like this:
`this.http.get(currentItem.imageUrl, {
  responseType: 'blob',
  headers: this.config.httpHeaders,
}).subscribe(
  (data: Blob) => {
    if ((this.config.maxCacheSize > -1 && this.currentCacheSize > this.config.maxCacheSize) || this.config.maxCacheSize == -1) {
      this.file.writeFile(localDir, fileName, data, {replace: true}).then((file: FileEntry) => {
        this.addFileToIndex(file).then(() => {
          this.getCachedImagePath(currentItem.imageUrl).then((localUrl) => {
            currentItem.resolve(localUrl);
            resolve();
            done();
            this.maintainCacheSize();
          });
        });
      }).catch((e) => {
        //Could not write image
        error(e);
      });
    } else {
      //if there is too less space
      currentItem.resolve(currentItem.imageUrl);
      resolve();
      done();
      this.maintainCacheSize();
    }
  },
  (e) => {
    //Could not get image via httpClient
    error(e);
  }
);`

**Comment by felixbroehl** [comment] 2018-07-04 22:12
@eduardoRoth can you test this?

**Comment by gmosornoza** [comment] 2018-07-04 22:19
It doesn't work for me.

The file is downloaded, but when its written to the filesystem, the filesize keeps 0.

I setup the maximum cache size, tried to move cordova.js after polifyll but no success.

**Comment by eduardoRoth** [comment] 2018-07-04 22:39
@felixbroehl made the following change instead:

*this is using your updated condition*
```
private get shouldIndex(): boolean {
    return (this.config.maxCacheSize > -1 && this.currentCacheSize > this.config.maxCacheSize) || this.config.maxCacheSize == -1;
  }
```

*Check if we have enough space in cache, if not, make some more removing the oldest one.*
```
   this.file.writeFile(localDir, fileName, data, {replace: true}).then((file: FileEntry) => {
              if (!this.shouldIndex) {
                this.maintainCacheSize();
              }
              this.addFileToIndex(file).then(() => {
                this.getCachedImagePath(currentItem.imageUrl).then((localUrl) => {
                  currentItem.resolve(localUrl);
                  resolve();
                  done();
                  this.maintainCacheSize();
                });
              });
            }).catch((e) => {
              //Could not write image
              error(e);
            });
```

**Comment by felixbroehl** [comment] 2018-07-04 22:42
maybe we should rename shouldIndex to isCacheSpaceExceeded or something like that

**Comment by gmosornoza** [comment] 2018-07-04 22:43
Hi,

It worked changing the order of cordova.js and polifyll.js.

@eduardoRoth I was doing it wrong!  The file to be edited is under /src/index.html (i was editing www/index.html)

Thank you all, it's working fine now.

**Comment by ajsystem** [comment] 2018-07-04 22:59
@felixbroehl same problem on Android 7.0.1

**Comment by felixbroehl** [comment] 2018-07-04 23:06
so maintainCacheSize already checking this. So I created a fork for this: https://github.com/felixbroehl/ionic-image-loader

Can somebody test this?
If its not working please also try to change the order of cordova.js and polyfill.js in your src/index.html

**Comment by eduardoRoth** [comment] 2018-07-04 23:32
Also created a fork with this change, but removed `shouldIndex` property as it was only used just in that function and other with similar functionality.

Tested in device and emulator and works.

This **does not** fixes the `polyfill.js` workaround.

Pull request https://github.com/zyra/ionic-image-loader/pull/171

**Comment by felixbroehl** [comment] 2018-07-04 23:41
Your fork seems good. I think we should document the polyfill.js workaround in the README and also ask @ihadeed to evaluate if there are consequences.

To bring @ihadeed up to date: It seems like the @ionic-native/file or cordova-plugin-file is not working correctly (promise resolve of this.file.writeFile is not called). Therefor images are not loaded on the first time. changing the order of cordova.js and polyfill.js in the src/index.html seems to do the trick.

**Comment by eduardoRoth** [comment] 2018-07-05 00:19
@ihadeed @felixbroehl 

Created PR https://github.com/zyra/ionic-image-loader/pull/173 with suggested `README.md`changes.

**Closed** 2018-08-01 08:43 UTC
Labels: bug
